# Generated by Django 6.0.2 on 2026-02-26 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tugassubmission_catatan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('tugas_baru', 'Tugas Baru'), ('materi_baru', 'Materi Baru'), ('deadline', 'Deadline Mendekat'), ('pengumuman', 'Pengumuman Baru')], max_length=20)),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('dibaca', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
