# Generated by Django 6.0.2 on 2026-02-26 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notifikasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tugassubmission',
            name='dinilai_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penilaian_diberikan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tugassubmission',
            name='dinilai_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tugassubmission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback dari dosen/admin'),
        ),
        migrations.AddField(
            model_name='tugassubmission',
            name='nilai',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nilai 0–100', max_digits=5, null=True),
        ),
    ]
