# Generated by Django 6.0.2 on 2026-03-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tugassubmission_dinilai_oleh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='tipe',
            field=models.CharField(choices=[('tugas_baru', 'Tugas Baru'), ('materi_baru', 'Materi Baru'), ('deadline', 'Deadline Mendekat'), ('pengumuman', 'Pengumuman Baru'), ('absensi', 'Absensi'), ('izin', 'Izin Absen')], max_length=20),
        ),
    ]
