# Generated by Django 6.0.2 on 2026-02-26 03:46

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0004_pengumuman_diedit_pada_pengumuman_embed_url_komentar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=tasks.models.materi_upload_path)),
                ('nama_file', models.CharField(blank=True, max_length=255)),
                ('ukuran', models.PositiveBigIntegerField(default=0)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('diedit_pada', models.DateTimeField(blank=True, null=True)),
                ('diunggah_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_diunggah', to=settings.AUTH_USER_MODEL)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='attendance.matakuliah')),
            ],
            options={
                'ordering': ['-diunggah_pada'],
            },
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diedit_pada', models.DateTimeField(blank=True, null=True)),
                ('file_soal', models.FileField(blank=True, null=True, upload_to=tasks.models.tugas_soal_upload_path)),
                ('nama_file_soal', models.CharField(blank=True, max_length=255)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_dibuat', to=settings.AUTH_USER_MODEL)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='attendance.matakuliah')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='TugasSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_jawaban', models.FileField(upload_to=tasks.models.tugas_submission_upload_path)),
                ('nama_file', models.CharField(blank=True, max_length=255)),
                ('ukuran', models.PositiveBigIntegerField(default=0)),
                ('catatan', models.TextField(blank=True, help_text='Catatan opsional dari mahasiswa')),
                ('dikumpulkan_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.tugas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dikumpulkan_pada'],
                'unique_together': {('tugas', 'user')},
            },
        ),
    ]
