# Generated by Django 6.0.2 on 2026-02-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugassubmission',
            name='catatan',
            field=models.TextField(blank=True),
        ),
    ]
