# Generated by Django 6.0.2 on 2026-02-25 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertemuan',
            name='batas_absen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertemuan',
            name='waktu_mulai',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
