# Generated by Django 6.0.2 on 2026-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_pengumuman_diedit_pada_pengumuman_embed_url_komentar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertemuan',
            name='kode_absen',
            field=models.CharField(blank=True, help_text='Kode 6 karakter untuk absensi, auto-generate.', max_length=6),
        ),
    ]
