# Generated by Django 6.0.2 on 2026-03-03 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0006_izinabsen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalStatis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruang', models.CharField(blank=True, max_length=50)),
                ('dosen', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=10)),
                ('link_online', models.URLField(blank=True, help_text='Link Zoom/Meet jika online')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_statis', to='attendance.matakuliah')),
            ],
            options={
                'verbose_name': 'Jadwal Statis',
                'verbose_name_plural': 'Jadwal Statis',
                'ordering': ['hari', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='JadwalDinamis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_asli', models.DateField(help_text='Tanggal pertemuan yang terpengaruh')),
                ('tipe', models.CharField(choices=[('cancel', 'Kelas Dibatalkan'), ('reschedule', 'Pindah Jadwal'), ('mode', 'Ganti Mode'), ('info', 'Informasi')], max_length=20)),
                ('tanggal_baru', models.DateField(blank=True, null=True)),
                ('jam_mulai_baru', models.TimeField(blank=True, null=True)),
                ('jam_selesai_baru', models.TimeField(blank=True, null=True)),
                ('ruang_baru', models.CharField(blank=True, max_length=50)),
                ('mode_baru', models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=10)),
                ('link_online', models.URLField(blank=True)),
                ('catatan', models.TextField(blank=True, help_text='Alasan/keterangan tambahan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_dinamis', to='attendance.matakuliah')),
                ('jadwal_statis', models.ForeignKey(blank=True, help_text='Kosongkan jika ini jadwal tambahan (tidak ada di statis)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='jadwal.jadwalstatis')),
            ],
            options={
                'verbose_name': 'Perubahan Jadwal',
                'verbose_name_plural': 'Perubahan Jadwal',
                'ordering': ['-tanggal_asli'],
            },
        ),
    ]
