# Generated by Django 6.0.2 on 2026-02-25 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_pertemuan_batas_absen_pertemuan_waktu_mulai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('prioritas', models.CharField(choices=[('normal', 'Normal'), ('penting', 'Penting'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('pinned', models.BooleanField(default=False)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumuman_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PengumumanDibaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibaca_pada', models.DateTimeField(auto_now_add=True)),
                ('pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibaca_oleh', to='attendance.pengumuman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pengumuman')},
            },
        ),
    ]
