# Generated by Django 6.0.2 on 2026-02-25 07:46

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_pengumuman_pengumumandibaca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='diedit_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='embed_url',
            field=models.URLField(blank=True, help_text='Link YouTube atau URL lainnya', null=True),
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diedit_pada', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='attendance.komentar')),
                ('pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='attendance.pengumuman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PengumumanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=attendance.models.pengumuman_upload_path)),
                ('tipe', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('file', 'File')], max_length=10)),
                ('nama_asli', models.CharField(blank=True, max_length=255)),
                ('ukuran', models.PositiveBigIntegerField(default=0, help_text='Ukuran file dalam bytes')),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='attendance.pengumuman')),
            ],
        ),
        migrations.CreateModel(
            name='PengumumanLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='attendance.pengumuman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pengumuman')},
            },
        ),
    ]
